def set_hant(self):
    self.ui.cc1.setText("選弓箭手")
    self.ui.cc2.setText("選騎士")
    self.ui.play.setText("開始遊戲")
    self.ui.cc3.setText("魔法師")
    self.ui.cc4.setText("刺客")
    self.ui.Archer.setText("弓箭手")
    self.ui.Knight.setText("騎士")
    self.ui.Magician.setText("魔法師")
    self.ui.Assassin.setText("刺客")

def set_hans(self):
    self.ui.cc1.setText("選弓箭手")
    self.ui.cc2.setText("選騎士")
    self.ui.play.setText("開始遊戲")
    self.ui.cc3.setText("魔法師")
    self.ui.cc4.setText("刺客")
    self.ui.Archer.setText("弓箭手")
    self.ui.Knight.setText("騎士")
    self.ui.Magician.setText("魔法師")
    self.ui.Assassin.setText("刺客")
    self.ui.now_choose.setText("您將以"+displaync+"進行遊戲")
    
def set_ja(self):
    self.ui.cc1.setText("選弓箭手")
    self.ui.cc2.setText("選騎士")
    self.ui.play.setText("開始遊戲")
    self.ui.cc3.setText("魔法師")
    self.ui.cc4.setText("刺客")
    self.ui.Archer.setText("弓箭手")
    self.ui.Knight.setText("騎士")
    self.ui.Magician.setText("魔法師")
    self.ui.Assassin.setText("刺客")
    self.ui.now_choose.setText("您將以"+displaync+"進行遊戲")