def set_hant(self):
    self.ui.label_Music.setText("音樂：")
    self.ui.Windowed_Settings.setText("視窗化")
    self.ui.label_Resolution.setText("解析度：")
    self.ui.Button_Play.setText("選擇職業")
    self.ui.Graphics_Settings.setTitle("顯示設定")
    self.ui.Music_On.setText("開啟")
    self.ui.Music_Off.setText("關閉")
    self.ui.Button_Reset.setText("重設")
    self.ui.Button_Save.setText("儲存")

def set_hans(self):
    self.ui.label_Music.setText("音乐：")
    self.ui.Windowed_Settings.setText("窗口化")
    self.ui.label_Resolution.setText("分辨率：")
    self.ui.Button_Play.setText("选择职业")
    self.ui.Graphics_Settings.setTitle("显示设置")
    self.ui.Music_On.setText("开启")
    self.ui.Music_Off.setText("关闭")
    self.ui.Button_Reset.setText("重置")
    self.ui.Button_Save.setText("保存")
    
def set_ja(self):
    self.ui.label_Music.setText("音楽：")
    self.ui.Windowed_Settings.setText("ウィンドウ")
    self.ui.label_Resolution.setText("解像度：")
    self.ui.Button_Play.setText("プレイヤーを\n選択")
    self.ui.Graphics_Settings.setTitle("グラフィック設定")
    self.ui.Music_On.setText("オン")
    self.ui.Music_Off.setText("オフ")
    self.ui.Button_Reset.setText("リセット")
    self.ui.Button_Save.setText("セーブ")